const ClientImages = [
  { id: 1, src: 'amura.svg', title: 'amura', alt: 'amura' },
  {
    id: 2,
    src: 'aspherica.svg',
    title: 'aspherica',
    alt: 'aspherica',
  },
  {
    id: 3,
    src: 'bpr-dp-taspen.svg',
    title: 'bpr-dp-taspen',
    alt: 'bpr-dp-taspen',
  },
  {
    id: 4,
    src: 'direktorat-kemahasiswaan-karir-ipb.svg',
    title: 'direktorat-kemahasiswaan-karir-ipb',
    alt: 'direktorat-kemahasiswaan-karir-ipb',
  },
  {
    id: 5,
    src: 'dompet-dhuafa.svg',
    title: 'dompet-dhuafa',
    alt: 'dompet-dhuafa',
  },
  {
    id: 6,
    src: 'dramaga-tower.svg',
    title: 'dramaga-tower',
    alt: 'dramaga-tower',
  },
  {
    id: 7,
    src: 'ipb-baru.svg',
    title: 'ipb-baru.svg',
    alt: 'ipb-baru.svg',
  },
  {
    id: 8,
    src: 'kemenpora.svg',
    title: 'kemenpora',
    alt: 'kemenpora',
  },
  {
    id: 9,
    src: 'labschool-anak-ipb.svg',
    title: 'labschool-anak-ipb',
    alt: 'labschool-anak-ipb',
  },
  {
    id: 10,
    src: 'mandiri-syariah.svg',
    title: 'mandiri-syariah',
    alt: 'mandiri-syariah',
  },
  {
    id: 11,
    src: 'masyarakat-mandiri.svg',
    title: 'masyarakat-mandiri',
    alt: 'masyarakat-mandiri',
  },
  {
    id: 12,
    src: 'olu-coffee-kitchen.svg',
    title: 'olu-coffee-kitchen',
    alt: 'olu-coffee-kitchen',
  },
  {
    id: 13,
    src: 'ristekdikti.svg',
    title: 'ristekdikti',
    alt: 'ristekdikti',
  },
  {
    id: 14,
    src: 'sablon-bogor.svg',
    title: 'sablon-bogor',
    alt: 'sablon-bogor',
  },
  {
    id: 15,
    src: 'swara-yasmin.svg',
    title: 'swara-yasmin',
    alt: 'swara-yasmin',
  },
  {
    id: 16,
    src: 'yayasan-bakti-insani.svg',
    title: 'yayasan-bakti-insani',
    alt: 'yayasan-bakti-insani',
  },
  {
    id: 17,
    src: 'dibalik-layar.svg',
    title: 'dibalik-layar',
    alt: 'dibalik-layar',
  },
  {
    id: 18,
    src: 'radar-bogor.svg',
    title: 'radar-bogor',
    alt: 'radar-bogor',
  },
  {
    id: 19,
    src: 'tebar-aqiqah.svg',
    title: 'tebar-aqiqah',
    alt: 'tebar-aqiqah',
  },
  {
    id: 20,
    src: 'tribun-bogor.svg',
    title: 'tribun-bogor',
    alt: 'tribun-bogor',
  },
  {
    id: 21,
    src: 'weding-design-bogor.svg',
    title: 'wedding-design-bogor',
    alt: 'wedding-design-bogor',
  },
];

export default ClientImages;
